=== Venn06/wsd201710/UTStutor/web/WEB-INF/students.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <!-- Type Declarations -->
    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9\.]+@[a-z\-]+(\.[a-z]+)+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][a-z]+( [A-Z][a-z]+)*"
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="password">
        <xs:restriction base="xs:string">
            <xs:pattern value=".{6,16}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="date">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}"
        </xs:restriction>
    </xs:simpleType>
    <!-- Element Declarations -->
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="email" type="email"/>
                            <xs:element name="name" type="name"/>
                            <xs:element name="password" type="password"/>
                            <xs:element name="DOB" type="date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Venn06/wsd201710/UTStutor/web/WEB-INF/students.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<students
    xmlns="http://www.uts.edu.au/31284/wsd-students"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-students students.xsd"
>
    <student>
        <email>ryan@ryanheise.com</email>
        <name>Ryan Heise</name>
        <password>blahblah</password>
        <DOB>2017-10-04</DOB>
    </student>
    <student>
        <email>joe@bloggs.com</email>
        <name>Joe Bloggs</name>
        <password>password</password>
        <DOB>2017-10-04</DOB>
    </student>
</students>
