=== Venn06/wsd201710/UTStutor/web/WEB-INF/tutors.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <!-- Type Declarations -->
    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9\.]+@[a-z\-]+(\.[a-z]+)+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][a-z]+( [A-Z][a-z]+)*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="password">
        <xs:restriction base="xs:string">
            <xs:pattern value=".[6,16]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="date">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="subject">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]*[a-z]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="status">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]*"/>
        </xs:restriction>
    </xs:simpleType>
    <!-- Element Declaration -->
    <xs:element name="tutors">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tutor" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="email" type="email"/>
                            <xs:element name="name" type="name"/>
                            <xs:element name="password" type="password"/>
                            <xs:element name="DOB" type="date"/>
                            <xs:element name="subject" type="subject"/>
                            <xs:element name="status" type="status"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Venn06/wsd201710/UTStutor/web/WEB-INF/tutors.xml
<?xml version="1.0" encoding="UTF-8"?>
<tutors
    xmlns="http://www.uts.edu.au/31284/wsd-tutors"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-tutors tutors.xsd"
>
    <tutor>
        <email>tutor1@uts.com</email>
        <name>Tutor Aa</name>
        <password>password1</password>
        <DOB>2017-10-04</DOB>
        <subject>WSD</subject>
        <status>available</status>
    </tutor>
    <tutor>
        <email>tutor2@uts.com</email>
        <name>Tutor Bb</name>
        <password>password2</password>
        <DOB>2017-10-04</DOB>
        <subject>USP</subject>
        <status>available</status>
    </tutor>
</tutors>
